environment:
  COVERALLS_REPO_TOKEN:
    secure: nawPdszJTzIQ4ZSOlJIUcg8VdWOT+da4eB/VKuF6eUTK502B6dNIw+R2DA4OJxWc
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      PYTHON_VERSION: "3.5"
      PYTHONPATH: "$HOME/.local/lib/python3.5/site-packages/"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      PYTHON_VERSION: "3.6"
      PYTHONPATH: "$HOME/.local/lib/python3.6/site-packages/"

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
      PYTHON_VERSION: "3.7"
      PYTHONPATH: "$HOME/.local/lib/python3.7/site-packages/"

stack: python %PYTHON_VERSION%

init:
  - echo %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - echo \"%APPVEYOR_SCHEDULED_BUILD%\"

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'
  
  # Linux
  - '$HOME/.pip/wheels'

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Configure headless CI for Linux. From https://electronjs.org/docs/tutorial/testing-on-headless-ci
  - sh: sudo apt-get install xvfb
  - sh: export DISPLAY=':99.0'
  - sh: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
  #Using pip install wxpython on Linux takes waaay too long, so downloading precompiled version instead
  - sh: pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"

  # Upgrade to the latest pip.
  - python -m pip install -U pip setuptools wheel

  # Install the PyInstaller test dependencies.
  - pip install -U -r requirements.txt -r requirements_gui.txt -r ./tests/requirements_test.txt

  # For CI - Coveralls.io
  - pip install -U coveralls



build_script:
  # Build and install PaGS
  - python setup.py build install --user

test_script:
  # Run pytest
  - python -m pytest --log-level DEBUG --junitxml=out_report.xml --cov=PaGS

  # Upload coverage to coveralls
  - coveralls

on_finish:
# upload test results to AppVeyor
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\out_report.xml))
