image:
- Visual Studio 2017

environment:
  matrix:
    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - ECHO \"%APPVEYOR_SCHEDULED_BUILD%\"

cache:
  # Cache downloaded pip packages and built wheels.
  - '%LOCALAPPDATA%\pip\Cache\http'
  - '%LOCALAPPDATA%\pip\Cache\wheels'

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import sys, platform, struct;
    print(sys.platform, platform.machine(), struct.calcsize('P')*8)"

  # Upgrade to the latest pip.
  - python -m pip install -U pip setuptools wheel

  # Install the PyInstaller test dependencies.
  - pip install -U -r requirements.txt -r requirements_gui.txt -r ./tests/requirements_test.txt

build_script:
  # Build and install PaGS
  - python setup.py build install --user

test_script:
  # Run pytest
  - python -m pytest --log-level DEBUG --junitxml=out_report.xml

on_finish:
# upload test results to AppVeyor
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\out_report.xml))